swsnu/swpp2021-team3

frontend/gaejosim/package.json, frontend/gaejosim/src/App.js, frontend/gaejosim/src/Component/CommonSearch/CommonSearch.js, frontend/gaejosim/src/Component/CommonSearch/TagView/TagView.js, frontend/gaejosim/src/Component/MatchInfo/MatchInfo.js, frontend/gaejosim/src/Component/MatchInfo/MatchMate/MatchMate.js, frontend/gaejosim/src/Component/MatchInfo/MatchMateList.js, frontend/gaejosim/src/Component/MatchInfo/TeamMate/TeamMate.js, frontend/gaejosim/src/Component/MatchInfo/TeamMateList.js, frontend/gaejosim/src/Component/MultiSearch.js, frontend/gaejosim/src/Component/ReportedUser/ReportedUserList.js, frontend/gaejosim/src/Component/ReportedUser/User.js, frontend/gaejosim/src/Component/Searchbar/Searchbar.js, frontend/gaejosim/src/Component/Statistic/Statistic.js, frontend/gaejosim/src/Container/Header/Header.js, frontend/gaejosim/src/Page/FindUserInfoPage.js, frontend/gaejosim/src/Page/LoginPage.js, frontend/gaejosim/src/Page/MultiSearchResultPage.js, frontend/gaejosim/src/Page/MyPage.js, frontend/gaejosim/src/Page/MyReportPage.js, frontend/gaejosim/src/Page/ReportActionPage.js, frontend/gaejosim/src/Page/ReportAuthPage.js, frontend/gaejosim/src/Page/SearchPage.js, frontend/gaejosim/src/Page/SignupPage.js, frontend/gaejosim/src/Page/SingleSearchResultPage.js, frontend/gaejosim/yarn.lock, frontend/package.json, frontend/yarn.lock
- Implementation of Search page and Some components related to MultiSearchResult Page.
- Implementation of all page routing on frontend
- Search page features implemented 
- Can route all pages
=> #32 feature/search

frontend/gaejosim/src/Component/CommonSearch/CommonSearch.js, frontend/gaejosim/src/Component/CommonSearch/TagView/TagView.js, frontend/gaejosim/src/Component/MatchInfo/MatchInfo.js, frontend/gaejosim/src/Component/MatchInfo/MatchMate/MatchMate.js, frontend/gaejosim/src/Component/MatchInfo/TeamMate/TeamMate.js, frontend/gaejosim/src/Component/Searchbar/Searchbar.js, frontend/gaejosim/src/Component/Statistic/Statistic.js, frontend/gaejosim/src/Page/SearchPage.js, frontend/gaejosim/src/Page/SingleSearchResultPage.js
Implementation of SingleSearchResult Page.
Implemented singleSearchResult Page. but we need to connect backend via axios.
=> #36_feature/searchResult

frontend/gaejosim/src/Component/MultiSearch.js
Implementing Report Auth Component axios post and get calls.
Implementation Report Auth Component axios post and get calls. (need to check)
=> #40 feature/report

backend/gaejosim/report/views.py, backend/gaejosim/search/views.py, backend/gaejosim/user/views.py, frontend/gaejosim/package.json, frontend/gaejosim/src/Component/MultiSearch.js, frontend/gaejosim/src/Component/Searchbar/Searchbar.js, frontend/package.json
- fix the parameter string parsing error from the client-side
- RIOT API Key update
- correct parameter delivery
- solve 500 solve Riot API Key
=> #43_feature/parameter-parsing-error

backend/gaejosim/report/views.py, backend/gaejosim/search/views.py, backend/gaejosim/user/views.py, frontend/gaejosim/src/App.js, frontend/gaejosim/src/Component/CommonSearch/CommonSearch.js, frontend/gaejosim/src/Component/CommonSearch/TagView/TagView.js, frontend/gaejosim/src/Component/MultiSearch.js, frontend/gaejosim/src/Component/ReportAction/ReportAction.js, frontend/gaejosim/src/Component/ReportAuth/ReportAuth.js, frontend/gaejosim/src/Component/Searchbar/Searchbar.js, frontend/gaejosim/src/Component/Statistic/Statistic.js, frontend/gaejosim/src/Page/MultiSearchResultPage.js
Implementation of axios on MultiSearh and ReortAuth
Update riot token
axios implemented.
Rion token updated.
=> fix: Implementation of axios on reportAuth and MultiSearchPage

frontend/gaejosim/src/Component/ReportAction/ReportAction.js, frontend/gaejosim/src/Component/ReportAuth/ReportAuth.js, frontend/gaejosim/src/Page/ReportActionPage.js
Axios implementation on reportAction page
Implemented all axios for mid Demo
=> fix: reportAction page axios

frontend/gaejosim/src/Component/CommonSearch/ResultView/Result.js, frontend/gaejosim/src/Component/ReportAuth/ReportAuth.css, frontend/gaejosim/src/Component/ReportAuth/ReportAuth.js, frontend/gaejosim/src/Component/Statistic/Statistic.css, frontend/gaejosim/src/Container/Header/Header.js, frontend/gaejosim/src/Page/ReportActionPage.css, frontend/gaejosim/src/Page/ReportActionPage.js, frontend/gaejosim/src/Page/ReportAuthPage.js, frontend/gaejosim/src/Page/SearchPage.css, frontend/gaejosim/src/Page/SearchPage.js
- Implementation of all core features for mid presesntation
- Implemented CSS with reportAction, reportAuth, searh and MultiSearchResult Pages.
=> #53_feature/mid_demo_css

.travis.yml
Resolves #57. (This will automatically close the corresponding issue when the PR is merged. If you do not want, remove the issue from the `Linked Issues` tab.)
- Add Coveralls to our travis to measure code coverage
- Measuring code coverage is possible!
- I have added a few more commits on top of #58. It is up to you either to merge this PR or to re-implement #58 based on this PR.
- Fix lint errors and SonarCloud security hotspots, if any
=> Add CoverAlls and refactor Travis config

.travis.yml
- To fix the backend directory
- To fix the backend directory
=> fix:backend root

.travis.yml, sonar-project.properties
- to test merge
- testing merge branch
=> #60 feature/coveralls python

backend/gaejosim/report/tests.py
- add a testcase to reach 100% backend coverage
- 100% backend coverage
=> #64_feature/add_report_test

.travis.yml
- exclude some files from backend test
- exclude some files from backend test
=> #72_feautre/test_exclusion

frontend/gaejosim/src/Component/Searchbar/Searchbar.test.js, frontend/gaejosim/src/Page/SearchPage.test.js, frontend/gaejosim/src/Page/SingleSearchResultPage.js, frontend/gaejosim/src/Page/SingleSearchResultPage.test.js
Coverage 79.415%
Coverage 79.415%
=> #70 feature/buttontest

backend/gaejosim/report/views.py, backend/gaejosim/search/views.py, backend/gaejosim/user/views.py
- update riot api key (2021.11.13)
- enable all server riot api calls
=> #75_feature/update_riot_key

backend/gaejosim/report/views.py, backend/gaejosim/search/views.py, backend/gaejosim/user/views.py
- to update RIOT API key
- Correctly working server w/ valid API key
=> #81 feature/update RIOT API key

backend/gaejosim/user/tests.py, backend/gaejosim/user/urls.py, backend/gaejosim/user/views.py
- to add logout function
- user can logout
- After logout, user cannot use report & apology function
=> #91 feature/logout

backend/gaejosim/core/utils.py, backend/gaejosim/report/tests.py, backend/gaejosim/report/views.py, backend/gaejosim/search/views.py, backend/gaejosim/user/views.py
- Fix authentication bug
- Add util functions to check RIOT timeout errors
- update RIOT API keys
- No bugs with report authentication / Timeout
=> fix: report authentication bug

backend/gaejosim/search/tests.py, backend/gaejosim/search/views.py
- To fix multi search url
- New multisearch URL!
=> fix:multi-search url fix

backend/gaejosim/core/utils.py, backend/gaejosim/report/views.py, backend/gaejosim/user/tests.py, backend/gaejosim/user/views.py
- To process not logged in error with one decorator 
- can process not logged in error with one decorator
=> feat: check logged in decorator

backend/gaejosim/user/tests.py, backend/gaejosim/user/views.py
- To fix the number of reports on my page
- Client side gets two reports on my page
=> fix: get two reports on my page

backend/gaejosim/report/tests.py, backend/gaejosim/report/urls.py, backend/gaejosim/report/views.py, backend/gaejosim/user/urls.py
- To add per-view cache and query cache for repeatedly called APIs
You can get faster result from server-side with below APIs
**per-view cache**
- mypage
- reports_statistics
- report_authentication
- my_reports
- my_received_reports
**query cache**
- report_statistics 에 today, total reports num
=> feat: add local cache

.travis.yml, backend/gaejosim/report/tests.py, backend/gaejosim/report/urls.py, backend/gaejosim/report/views.py, backend/gaejosim/search/views.py, backend/gaejosim/user/views.py
- delete report
- user can delete his or her report
=> #85_feature/delete_report

backend/gaejosim/gaejosim/urls.py, backend/gaejosim/user/urls.py
- delete cache & change riot.txt url
- delete cache & change riot.txt url
=> #214 fix/delete cache

backend/gaejosim/report/urls.py, backend/gaejosim/report/views.py, backend/gaejosim/search/views.py, backend/gaejosim/user/views.py
=> fix:update riot key

backend/gaejosim/report/views.py, backend/gaejosim/search/views.py, backend/gaejosim/user/views.py
-  change error message for ML error
- The message will be in Korean
=> #219_fix/ML_error_message

backend/gaejosim/report/views.py, backend/gaejosim/search/views.py, backend/gaejosim/user/views.py
=> #221_fix/update_riot_key
